version: "3"

services:
  filebrowser:
    image: aria2-ui:latest
    volumes:
      - ./data:/data
      - ./sslkey:/app/conf/key
      - ./aria2:/app/conf/aria2.conf
      - ./app/filebrowser.db:/app/filebrowser.db
    environment:
      - PUID=1000
      - PGID=1000
      - DOMAIN=https://subdomain.example.com
      - SSL=true
      - RPC_SECRET=aria2
      - ARIA2_USER=admin
      - ARIA2_PWD=password
      - ENABLE_AUTH=true
    restart: unless-stopped
  plex:
    image: plex-media-server
    volumes:
      - ./data:/media:rw 
      - ./transcode:/transcode
      - ./config:/config 
    environment:
      - LOG_DEBUG=0
      - LOG_VERBOSE=0
      - PLEX_CLAIM=claim-7KUpCHxW6yozR56UA1YL 
    restart: unless-stopped
    hostname: "moe-plex-server"  
networks:
  default:
    name: join
    external: true

