version: '3.3'
services:
  pagermaid_pyro:
    container_name: PGP
    hostname: PGP
    privileged: true
    image: pagermaid_pyro:latest
    restart: unless-stopped
    volumes:
      - ./:/.docker/pagermaid_pyro
    environment:
      - RUN_AS_ROOT=false   # 是否以root权限运行pagermaid，true为是，false为否
      - PUID=1000           # 当 RUN_AS_ROOT=false时才生效，即以普通用户权限运行pagermaid，可以修改为你定义用户的UID
      - PGID=1000    
