version: '3.3'
services:
  pagermaid_pyro:
    container_name: PGP
    hostname: PGP
    privileged: true
    image: pagermaid_pyro:latest
    restart: unless-stopped
    volumes:
      - ./:/pagermaid_pyro
    environment:
      - RUN_AS_ROOT=false
      - PUID=1000           
      - PGID=1000    
